# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafiopicpay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafiopicpay
  pod 'Kingfisher', '4.7'
  pod 'IQKeyboardManagerSwift'
  pod 'CryptoSwift'
  pod 'RealmSwift', '~> 3.10'
  
  target 'desafiopicpayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafiopicpayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
